"""empty message

Revision ID: 09881542d9ee
Revises: 136d98670f2c
Create Date: 2018-02-27 12:09:01.908597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09881542d9ee'
down_revision = '136d98670f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_guid', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('train_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bot_guid'], ['bots.bot_guid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training')
    # ### end Alembic commands ###
