"""empty message

Revision ID: 136d98670f2c
Revises: 8c1fb0c85922
Create Date: 2018-02-26 06:48:06.781212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136d98670f2c'
down_revision = '8c1fb0c85922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('last_trained', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'last_trained')
    # ### end Alembic commands ###
