"""empty message

Revision ID: 15a0d5918b55
Revises: 4c1efb781613
Create Date: 2017-08-27 01:06:32.988037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a0d5918b55'
down_revision = '4c1efb781613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intents', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intents', 'name')
    # ### end Alembic commands ###
