"""empty message

Revision ID: 2473a28c7d57
Revises: dfac8256fb75
Create Date: 2017-11-07 18:21:52.541582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2473a28c7d57'
down_revision = 'dfac8256fb75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('is_human', sa.Integer(), nullable=True))
    op.add_column('logs', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'source')
    op.drop_column('logs', 'is_human')
    # ### end Alembic commands ###
