"""empty message

Revision ID: 2a434178e651
Revises: f7d2c5e79edf
Create Date: 2017-09-26 13:26:04.591885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a434178e651'
down_revision = 'f7d2c5e79edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intents', sa.Column('patterns', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intents', 'patterns')
    # ### end Alembic commands ###
