"""empty message

Revision ID: 4098098fdff5
Revises: 605cff257d74
Create Date: 2017-08-27 04:20:59.304224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4098098fdff5'
down_revision = '605cff257d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intents', sa.Column('utterances', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('intents', 'intents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intents', sa.Column('intents', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('intents', 'utterances')
    # ### end Alembic commands ###
