"""empty message

Revision ID: 4c1efb781613
Revises: 8b1334917d4c
Create Date: 2017-08-26 20:40:21.761180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c1efb781613'
down_revision = '8b1334917d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_guid', sa.String(), nullable=True),
    sa.Column('intents', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('has_entities', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot_guid'], ['bots.bot_guid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intents')
    # ### end Alembic commands ###
