"""empty message

Revision ID: 5251a920f66b
Revises: 09881542d9ee
Create Date: 2018-02-27 13:04:38.893045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5251a920f66b'
down_revision = '09881542d9ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('training_time', sa.String(), nullable=True))
    op.drop_column('training', 'train_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('train_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('training', 'training_time')
    # ### end Alembic commands ###
