"""empty message

Revision ID: 550d19f4dca8
Revises: ac32745ef1af
Create Date: 2017-10-13 02:39:39.902267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550d19f4dca8'
down_revision = 'ac32745ef1af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_guid', sa.String(), nullable=True),
    sa.Column('kid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bot_guid'], ['bots.bot_guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge')
    # ### end Alembic commands ###
