"""empty message

Revision ID: 605cff257d74
Revises: 15a0d5918b55
Create Date: 2017-08-27 01:33:46.033956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '605cff257d74'
down_revision = '15a0d5918b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_guid', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('examples', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot_guid'], ['bots.bot_guid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entities')
    # ### end Alembic commands ###
