"""empty message

Revision ID: 8776c359acf6
Revises: dc37333a7fba
Create Date: 2017-09-22 13:04:14.170938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8776c359acf6'
down_revision = 'dc37333a7fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    # ### end Alembic commands ###
