"""empty message

Revision ID: 8c1fb0c85922
Revises: fdca80e072ee
Create Date: 2018-01-17 16:25:01.724541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1fb0c85922'
down_revision = 'fdca80e072ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intents', sa.Column('is_folder', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intents', 'is_folder')
    # ### end Alembic commands ###
