"""empty message

Revision ID: 9382097f8d3a
Revises: 0a48cf5e89f1
Create Date: 2017-09-25 20:14:11.095503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import JSON

# revision identifiers, used by Alembic.
revision = '9382097f8d3a'
down_revision = '0a48cf5e89f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intents', sa.Column('patterns', sa.ARRAY(JSON(astext_type=sa.Text())), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intents', 'patterns')
    # ### end Alembic commands ###
