"""empty message

Revision ID: a41c8adb542f
Revises: 8776c359acf6
Create Date: 2017-09-25 18:17:01.857836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41c8adb542f'
down_revision = '8776c359acf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intents', sa.Column('patterns', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intents', 'patterns')
    # ### end Alembic commands ###
