"""empty message

Revision ID: a795044cb0c7
Revises: 2a434178e651
Create Date: 2017-09-29 23:18:58.922503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a795044cb0c7'
down_revision = '2a434178e651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('words', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'words')
    # ### end Alembic commands ###
