"""empty message

Revision ID: aab555e68b46
Revises: 53c9ad0dab75
Create Date: 2017-11-07 17:52:50.890611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab555e68b46'
down_revision = '53c9ad0dab75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('is_human', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics', 'is_human')
    # ### end Alembic commands ###
