"""empty message

Revision ID: ac32745ef1af
Revises: cc5ef7ff8194
Create Date: 2017-10-08 17:09:51.748225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac32745ef1af'
down_revision = 'cc5ef7ff8194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('response_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics', 'response_time')
    # ### end Alembic commands ###
