"""empty message

Revision ID: cce4f2f8a253
Revises: a795044cb0c7
Create Date: 2017-10-02 23:28:32.076243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce4f2f8a253'
down_revision = 'a795044cb0c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('bot_guid', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('pat', sa.String(), nullable=True),
    sa.Column('pid', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    # ### end Alembic commands ###
