"""empty message

Revision ID: ccf2e14e1f1e
Revises: cce4f2f8a253
Create Date: 2017-10-06 16:29:33.148162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf2e14e1f1e'
down_revision = 'cce4f2f8a253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('intents_bot_guid_fkey', 'intents', type_='foreignkey')
    op.create_foreign_key(None, 'intents', 'bots', ['bot_guid'], ['bot_guid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'intents', type_='foreignkey')
    op.create_foreign_key('intents_bot_guid_fkey', 'intents', 'bots', ['bot_guid'], ['bot_guid'])
    # ### end Alembic commands ###
