"""empty message

Revision ID: dc37333a7fba
Revises: 44e65fe253c6
Create Date: 2017-09-19 12:43:17.213877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc37333a7fba'
down_revision = '44e65fe253c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_guid', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('entities', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('confident', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot_guid'], ['bots.bot_guid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analytics')
    # ### end Alembic commands ###
