"""empty message

Revision ID: dda83c07ffd9
Revises: 2473a28c7d57
Create Date: 2018-01-03 20:12:37.638505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda83c07ffd9'
down_revision = '2473a28c7d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intents', sa.Column('modified', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intents', 'modified')
    # ### end Alembic commands ###
