"""empty message

Revision ID: dfac8256fb75
Revises: d6b7eb801ea7
Create Date: 2017-11-07 18:17:19.922665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dfac8256fb75'
down_revision = 'd6b7eb801ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('user_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'user_data')
    # ### end Alembic commands ###
