"""empty message

Revision ID: e41ac40b2927
Revises: be7c225167b2
Create Date: 2017-08-14 22:01:29.178964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41ac40b2927'
down_revision = 'be7c225167b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
